info:
  contact: {}
paths:
  /douyin/user/login/:
    post:
      parameters:
      - description: username
        in: query
        name: username
        type: string
      - description: password
        in: query
        name: password
        type: string
      responses:
        "200":
          description: '{"Response":{},"UserId","","Token":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
swagger: "2.0"
